### PR TITLE
autoupdater: add upgrade.d directory.

### PR DESCRIPTION
**Pull request by lemoer**

### CODE REVIEW

**Comment by tcatm** [comment]
I think this should be preupgrade.

**Comment by lemoer** [comment]
I would appreciate if you can decide the name of the directory very fast, because I wan't to use the package during an update tomorrow.

**Comment by NeoRaider** [comment]
We've discussed the name on IRC, and decided on "upgrade.d" (as we can't possible have something like "post-upgrade" anyways).

**Comment by NeoRaider** [comment]
(also, download.d is also executed *before* the download of the image)

**Pull request merged**
