### PR TITLE
WIP: bump l3roamd to PR 59: Remove wired-clients by interpreting RTM_DELNEIGH

### PR DESCRIPTION
**Pull request by genofire**

### CODE REVIEW

**Comment by christf** [comment]
the patch for DELNEIGH is not ready yet. It works "in the lab" but not in the field.

**Comment by genofire** [comment]
I know, thats the reason, why i tag it with WIP ...
(i just need to path the gluon-packages for me - so it was just a click to make this PR for the future)

**Comment by rotanid** [comment]
https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by genofire** [comment]
Ah supi, github have something equal also, now.

**Comment by christf** [comment]
let's keep freifunk-gluon as repository for l3roamd. the one in christf is just a fork for my work.
Also there is #226 now

**Pull request closed without merging**
