### PR TITLE
Add new packages sse-multiplex and batman-adv-visdata

### PR DESCRIPTION
**Pull request by NeoRaider**

### CODE REVIEW

**Comment by NeoRaider** [comment]
Not tested of OpenWrt yet, but does compile now...

**Comment by NeoRaider** [comment]
I'm currently debugging a weird crash in sse-multiplexd, so this is not ready yet.

**Comment by NeoRaider** [comment]
The crash is fixed now.

**Comment by NeoRaider** [comment]
I've decided to reimplement batman-adv-visdata in C before merging this.

**Comment by rubo77** [comment]
Can you add a small description why this is needed?

Do server side events not work correctly in Freifunk?

**Comment by NeoRaider** [comment]
@rubo77, see the description of the sse-multiplex package: https://github.com/freifunk-gluon/packages/blob/sse-multiplex/net/sse-multiplex/Makefile#L17

The idea is to allow multiple viewers of the status page, while only needing a single backend process generating the event stream (instead of one per viewer).

**Pull request merged**
