### PR TITLE
autoupdater: Fix various possible nullpointer dereferences

### PR DESCRIPTION
**Pull request by TobleMiner**
The following commits fix some possible nullpointer dereferences due to failing dynamic memory allocations.

I've split the fixes into quite a few separate commits to make reviewing easier; just let me know in case you prefer fewer commits (1 per file or somehing)

Signed-off-by: Tobias Schramm tobleminer@gmail.com

### CODE REVIEW

**Comment by NeoRaider** [comment]
This adds a lot of boilerplate, and even tries to recover after an allocation failed in some places, which is not very useful in my opinion.

Let's add a few small helper functions like `safe_malloc()`, which do malloc, check the result, print an error message and `abort()` on failure; this way, the actual use sites aren't cluttered with error checks.

**Comment by TobleMiner** [comment]
Having a safe malloc function sounds like a good idea.

Recovering from failing signature allocations while parsing the manifest probably didn't make a lot of sense in the first place. If the manifest would still have enough valid signatures after recovering chances are wo don't have enough free memory to store the upgrade anyways. Thus aborting would be perferctly fine there, too.

**Comment by TobleMiner** [comment]
@NeoRaider I've rewritten the patches and updated the PR

**Comment by NeoRaider** [comment]
Thanks, I've merged this with a few changes (in particular, I removed the error message argument to keep the calls simple and added a *safe_realloc* helper.

Also, util.h was missing a stddef.h include for *size_t*.

**Comment by TobleMiner** [comment]
Uh, thanks for the fixups

**Pull request closed without merging**
