### PR TITLE
overcome tunneldigger state reset error in case of broken broker

### PR DESCRIPTION
**Pull request by cmarxmeier**
Fix for https://github.com/wlanslovenija/tunneldigger/issues/87
credits: RalfJung

tested in 2018.2.1 with gluon provided tunneldigger -> tunneldigger-2017-12-13-d7db3500:

PKG_SOURCE_URL:=git://github.com/wlanslovenija/tunneldigger.git
PKG_SOURCE_DATE:=2017-12-13
PKG_SOURCE_VERSION:=d7db350011076d6a83855d412885a29a7d142b6e

as base.

`Thu Mar 28 01:05:24 2019 daemon.info td-client: Selected fgw02.freifunk-siegburg.de:20003 as the best broker.
Thu Mar 28 01:05:25 2019 daemon.warn td-client: Received error response from broker!
Thu Mar 28 01:05:25 2019 daemon.err td-client: Connection to fgw02.freifunk-siegburg.de lost.
Thu Mar 28 01:05:25 2019 daemon.info td-client: Performing broker selection...
Thu Mar 28 01:05:25 2019 daemon.info td-client: Not trying fgw02.freifunk-siegburg.de:20003 again as it broke last time we tried.
Thu Mar 28 01:05:36 2019 daemon.err td-client: No suitable brokers found. Retrying in 5 seconds.
Thu Mar 28 01:05:41 2019 daemon.err td-client: Resetting status of brokers and starting from scratch.
Thu Mar 28 01:05:41 2019 daemon.info td-client: Performing broker selection...
Thu Mar 28 01:05:42 2019 daemon.debug td-client: Broker usage of fgw02.freifunk-siegburg.de:20003: 1663
Thu Mar 28 01:05:52 2019 daemon.info td-client: Selected fgw02.freifunk-siegburg.de:20003 as the best broker.
Thu Mar 28 01:05:53 2019 daemon.info td-client: Tunnel successfully established.
Thu Mar 28 01:05:53 2019 daemon.notice netifd: Interface 'mesh_vpn' is enabled
Thu Mar 28 01:05:53 2019 daemon.notice netifd: Network device 'mesh-vpn' link is up
Thu Mar 28 01:05:53 2019 daemon.notice netifd: Interface 'mesh_vpn' has link connectivity
Thu Mar 28 01:05:53 2019 daemon.notice netifd: Interface 'mesh_vpn' is setting up now
Thu Mar 28 01:05:54 2019 daemon.notice netifd: Interface 'mesh_vpn' is now up
`

### CODE REVIEW

**Comment by bobcanthelpyou** [comment]
Sorry but the log is hard to read isn't it?
```
Thu Mar 28 01:05:24 2019 daemon.info td-client: Selected fgw02.freifunk-siegburg.de:20003 as the best broker.
Thu Mar 28 01:05:25 2019 daemon.warn td-client: Received error response from broker!
Thu Mar 28 01:05:25 2019 daemon.err td-client: Connection to fgw02.freifunk-siegburg.de lost.
Thu Mar 28 01:05:25 2019 daemon.info td-client: Performing broker selection...
Thu Mar 28 01:05:25 2019 daemon.info td-client: Not trying fgw02.freifunk-siegburg.de:20003 again as it broke last time we tried.
Thu Mar 28 01:05:36 2019 daemon.err td-client: No suitable brokers found. Retrying in 5 seconds.
Thu Mar 28 01:05:41 2019 daemon.err td-client: Resetting status of brokers and starting from scratch.
Thu Mar 28 01:05:41 2019 daemon.info td-client: Performing broker selection...
Thu Mar 28 01:05:42 2019 daemon.debug td-client: Broker usage of fgw02.freifunk-siegburg.de:20003: 1663
Thu Mar 28 01:05:52 2019 daemon.info td-client: Selected fgw02.freifunk-siegburg.de:20003 as the best broker.
Thu Mar 28 01:05:53 2019 daemon.info td-client: Tunnel successfully established.
Thu Mar 28 01:05:53 2019 daemon.notice netifd: Interface 'mesh_vpn' is enabled
Thu Mar 28 01:05:53 2019 daemon.notice netifd: Network device 'mesh-vpn' link is up
Thu Mar 28 01:05:53 2019 daemon.notice netifd: Interface 'mesh_vpn' has link connectivity
Thu Mar 28 01:05:53 2019 daemon.notice netifd: Interface 'mesh_vpn' is setting up now
Thu Mar 28 01:05:54 2019 daemon.notice netifd: Interface 'mesh_vpn' is now up
```

**Comment by cmarxmeier** [comment]
no, it isn't.
Broker fgw02 marked broken - 
reset of brokers status
reset works ..
td-client connects to fgw02 this time.

this would be hard to read ( no idea about content):
年秋季，国际专家在当地专业人员，包括加沙伊斯兰大学建筑保护学科的教授们的协助下， 挽救了拜占庭遗址的关键部分，避免了倒塌和不可挽回的损失，如马赛克地板和据说埋葬着 Levant 修道院创始人圣希拉容遗体的地下室。

**Comment by bobcanthelpyou** [comment]
Sorry, i just meant that i am unable to read the log output without line breaks easily. It might just be me.

**Comment by cmarxmeier** [comment]
it's the original logread that shows, that patch works and broken status flags are now resetted - patch for tunneldigger repo will not have effect, cause gluon sticks on 2017 version - therefore this seperate patch.

**Comment by cmarxmeier** [comment]
error description on fix to be found here: https://forum.freifunk.net/t/tunneldigger-client-bei-gluon-2018-2-1-fixed/20337/15

**Comment by RalfJung** [comment]
> it's the original logread that shows, 

Then something is broken on your side, usually logread has newlines at the end of every message.

It looks like you use single-backtics `` ` `` instead of triple-backtics ```` ``` ``` around the log quote, which is why it gets rendered poorly.

Anyway, [this has now landed upstrem](https://github.com/wlanslovenija/tunneldigger/pull/88), so instead of adding a patch probably the upstream commit should be bumped?

**Comment by cmarxmeier** [comment]
gluon tunneldigger currently still sticks on ancient:
PKG_NAME:=tunneldigger
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=git://github.com/wlanslovenija/tunneldigger.git
PKG_SOURCE_DATE:=2017-12-13
PKG_SOURCE_VERSION:=d7db350011076d6a83855d412885a29a7d142b6e

that was the reason for backpatch - no idea what has changed in /wlanslovenija/tunneldigger.git since that point of time - testet patch based on this state.

**Comment by RalfJung** [comment]
It's not actually outdated, tunneldigger upstream just does not change much. Nothing changed in the tunneldigger client since d7db350011076d6a83855d412885a29a7d142b6e -- except for the PR that just landed.

**Comment by cmarxmeier** [comment]
so changing to :
PKG_NAME:=tunneldigger
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=git://github.com/wlanslovenija/tunneldigger.git
PKG_SOURCE_DATE:=2017-12-13
PKG_SOURCE_VERSION:=7c467e68021526b8631e8a53a9022aa223b1991c

would have the same result :D

**Pull request closed without merging**
