### PR TITLE
pretty-hostname: instantly apply hostname

### PR DESCRIPTION
**Pull request by mkg20001**
This makes it work like the CLI

### CODE REVIEW

**Review by mweinelt — APPROVED** [review]

**Comment by NeoRaider** [comment]
I don't really think this makes sense - the Lua library was intentionally more low-level than the CLI util; I'd generally expect UCI-based configuration not to have any effect until the next reboot / service restart. This is just my opinion though, so I won't ask for a revert, as it seems that @mweinelt is fine with the change.

**Comment by mkg20001** [comment]
Apply on restart doesn't really exist for the hostname, as there isn't a service to restart afaik. Adding it prob would be overkill so this sounds the sanest solution to me.

**Comment by NeoRaider** [comment]
The question is what the usecase is - at the moment all users of this library are part of the config mode or upgrade scripts, so the old hostname isn't really observable. Do you have custom packages that make use of the Lua library?

**Comment by mkg20001** [comment]
Yes. I've written one for funkfeuer graz that pulls data from manman.graz.funkfeuer.at (their node DB that contains OLSR addresses). It updates the ips & hostname and runs reconfigure&reload afterwards during runtime. So having the hostname update be visible instantly is cool.

(Also I'm currently working on OLSR support. https://github.com/mkg20001/gluon which ig we'd have to talk about, since upstreaming that is going to be effort)

**Pull request merged**
